insert into PERSONA(NOMBRE,APELLIDO,SEXO,FECHA_NACIMIENTO,CORREO,FECHA_REGISTRO)VALUES('LUIS','RODRIGUEZ','M','2017-08-08','ODI@ODI','2017-08-08');
insert into PROFESOR(RFC,CURP,IFE,CV,CVT,ID_PERSONA)VALUES('ESTO ES UN RFC','ESTE ES UN CURP','ESTE ES UN IFE','ESTO ES UN CV','ESTO ES UN CV TEXT',1);




insert into NIVEL_EDU(ID_NIVEL,NIVEL)VALUES(1,'Primaria');
insert into NIVEL_EDU(ID_NIVEL,NIVEL)VALUES(2,'Secundaria');
insert into NIVEL_EDU(ID_NIVEL,NIVEL)VALUES(3,'Bachillerato');
insert into NIVEL_EDU(ID_NIVEL,NIVEL)VALUES(4,'Universidad');
insert into NIVEL_EDU(ID_NIVEL,NIVEL)VALUES(5,'Maestria');
insert into NIVEL_EDU(ID_NIVEL,NIVEL)VALUES(6,'Doctorado');